# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  db_tests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d

      - name: DB Wait
        run: |
          # Wait for the database to be ready
          until docker exec db pg_isready -U postgres; do
            echo "Waiting for database..."
            sleep 2
          done
      
      - name: Run migrations
        run: ./migrate_all.sh localhost 5432 postgres database
    
      - name: Wait for API to be ready
        run: |
          until curl -i http://localhost:3001/ready | grep "OK"; do
            echo "Waiting for API..."
            sleep 2
          done
    
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc libcurl4-openssl-dev libjson-c-dev

      - name: Build upload binary
        run: gcc upload/main.c -lcurl -ljson-c -ggdb -o a.out

      - name: Start upload service
        run: |
          mkfifo test
          ./tests/run_upload.sh test &

      - name: Run tests
        run: ./db_tests.sh
      
      - name: Stop containers
        if: always()
        run: docker compose down
